import type { ProviderName } from "@/lib/research-types";
import { applyCitations } from "./citations";
import type { DeepResearchProvider, PollResult, StartResult } from "./types";

/**
 * Simulated providers for demos, local development and tests. They behave
 * like the real ones (async start → poll until done) but return a clearly
 * labelled placeholder report. Add `[mock-fail-openai]` or `[mock-fail-gemini]`
 * to a prompt to simulate a provider failure.
 */
export class MockDeepResearchProvider implements DeepResearchProvider {
  constructor(
    readonly name: ProviderName,
    private readonly durationMs: number,
    private readonly now: () => number = Date.now,
  ) {}

  async start({ prompt }: { prompt: string; researchId: string }): Promise<StartResult> {
    const fail = prompt.includes(`[mock-fail-${this.name}]`) ? "-fail" : "";
    // Use the first substantive line of the brief (skip preambles ending in ":").
    const firstLine = prompt.split("\n").map((l) => l.trim()).find((l) => l && !l.endsWith(":")) ?? prompt;
    const topic = Buffer.from(firstLine.slice(0, 200)).toString("base64url");
    return {
      externalId: `mock-${this.name}-${this.now()}-${this.durationMs}${fail}.${topic}`,
      model: this.name === "openai" ? "mock-deep-research" : "mock-gemini-deep-research",
      unavailableModels: [],
    };
  }

  async poll(externalId: string): Promise<PollResult> {
    const [head, topicB64 = ""] = externalId.split(".");
    const parts = head!.split("-");
    const startedAt = Number(parts[2]);
    const duration = Number(parts[3]);
    const fail = parts[4] === "fail";
    const elapsed = this.now() - startedAt;
    if (elapsed < duration) {
      const pct = Math.min(99, Math.round((elapsed / Math.max(duration, 1)) * 100));
      return { state: "running", remoteStatus: "in_progress", progressNote: `Simulated research ${pct}% complete` };
    }
    if (fail) {
      return { state: "failed", retryable: false, remoteStatus: "failed", error: `Simulated ${this.name} failure` };
    }
    const topic = Buffer.from(topicB64, "base64url").toString("utf8").split("\n")[0]!.trim() || "your topic";
    const { markdown, sources } = mockReport(this.name, topic);
    return {
      state: "completed",
      result: {
        markdown,
        sources,
        metadata: { remoteStatus: "completed", searchCount: 12, inputTokens: 1200, outputTokens: 3400, durationMs: elapsed },
      },
    };
  }

  async cancel(): Promise<void> {}
}

function mockReport(provider: ProviderName, topic: string) {
  const label = provider === "openai" ? "OpenAI" : "Gemini";
  const text = `# Research Report (simulated ${label} output)

> **Mock mode:** this report was generated by the built-in simulator because \`RESEARCH_MOCK_PROVIDERS=true\`. No live web research was performed and the entries below are placeholders that demonstrate structure and formatting only.

## Executive Summary

This simulated report responds to the brief: *${topic.replace(/[*_`]/g, "")}*. In live mode, ${label} Deep Research searches the web for several minutes and returns a long, cited report. The sections below mirror that structure — summary, findings, a comparison table, methodology, caveats and a conclusion — so the PDF and email pipeline can be exercised end to end without API keys.

## Key Findings

- **Finding one.** Primary sources are preferred over aggregators when confirming each item ([example.com](https://example.com/primary-source)).
- **Finding two.** Each claim carries an inline citation that becomes a numbered reference in the PDF ([example.org](https://example.org/secondary-source)).
- **Finding three.** Items that could not be verified are flagged in the caveats rather than silently included ([iana.org](https://www.iana.org/help/example-domains)).

## Comparison Table

| Item | Category | Evidence | Confidence | Notes |
|---|---|---|---|---|
| Placeholder A | Example | Official website statement | High | Verified on primary source |
| Placeholder B | Example | Interview / press coverage | Medium | Needs re-confirmation |
| Placeholder C | Example | Community reports only | Low | Treat as a lead |

## Methodology & Verification

1. Broad discovery searches to collect candidate items.
2. Verification against primary sources (official pages, documents).
3. Cross-checking with reputable secondary coverage and noting recency.

## Caveats

- Simulated content — do not rely on it.
- Live results depend on what is publicly documented at research time.

## Conclusion

Switch \`RESEARCH_MOCK_PROVIDERS\` to \`false\` and configure API keys to run real ${label} deep research.`;

  return applyCitations(text, [], { indexUnit: "utf16" });
}
